apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: ap-south-1
  tags:
    owner: HarishNShetty
    bu: hns
    environment: prod
    project: statefulsets-demo

availabilityZones:
  - ap-south-1a
  - ap-south-1b
  - ap-south-1c

iam:
  withOIDC: true

managedNodeGroups:
  - name: Worker-Node-Group
    instanceType: t3.small
    minSize: 4
    maxSize: 5
    privateNetworking: true
    volumeSize: 20
    # ssh:
    #   allow: true
      #publicKeyName: eks-vj-ohio
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: false
        certManager: false
        ebs: true
        fsx: false
        efs: false
        albIngress: true
        xRay: false
        cloudWatch: false
    labels:
      lifecycle: ec2-autoscaler
